version: '3.7'
services:
  haproxy:
    image: haproxy:2.4
    container_name: haproxy-lb
    restart: "no"
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    ports:
      - "4080:80"
      - "8404:8404"
      - "55432:5432"
      
  backend-3:
    image: postgres
    container_name: haproxy-backend-3
    restart: "no"
    volumes:
      - $PWD/dbslave_1/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "pass"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "15432:5432"
  
  backend-4:
    image: postgres
    container_name: haproxy-backend-4
    restart: "no"
    volumes:
      - $PWD/dbslave_2/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "pass"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "25432:5432"

  backend-5:
    image: postgres
    container_name: haproxy-backend-5
    restart: "no"
    volumes:
      - $PWD/dbslave_3/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "pass"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "65432:5432"

  dbmaster:
    image: postgres
    volumes:
      - $PWD/dbmaster/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "pass"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"

  frontend-1:
    build: .
    container_name: nginx-frontend-1
    command: >
      sh -c "pip install --upgrade pip &&
        python manage.py runserver 0.0.0.0:9000"
    env_file: .env
    volumes:
      - .:/usr/src/dm_rest
    ports:
      - 9000:9000
    depends_on:
      - backend-3
      - backend-4
      - dbmaster

  nginx:
    image: nginx:1.21
    container_name: nginx-lb
    restart: on-failure
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "4088:80"
      - "4098:8080"

  frontend-2:
    build: .
    container_name: nginx-frontend-2
    command: >
      sh -c "pip install --upgrade pip &&
        python manage.py runserver 0.0.0.0:4000"
    env_file: .env
    volumes:
      - .:/usr/src/dm_rest
    ports:
      - 4000:4000
    depends_on:
      - backend-3
      - backend-4
      - dbmaster

  frontend-3:
    build: .
    container_name: nginx-frontend-3
    command: >
      sh -c "pip install --upgrade pip &&
        python manage.py runserver 0.0.0.0:3000"
    env_file: .env
    volumes:
      - .:/usr/src/dm_rest
    ports:
      - 3000:3000
    depends_on:
      - backend-3
      - backend-4
      - dbmaster
